### PR TITLE
Add strict mode for false result

### PR DESCRIPTION
**Pull request by Rigorbb**

### CODE REVIEW

**Comment by wapmorgan** [comment]
So you propose false as result in case when no date&time information in provided string?

**Comment by Rigorbb** [comment]
Yes

**Comment by Rigorbb** [comment]
What is the status of this request?

**Comment by wapmorgan** [comment]
Thanks for suggestion, but the way you did it is not a good one. I've used your idea and realized this functionality: pass `true` as second argument in `parse($string, $falseWhenNotChanged)` call in **2.0.0** version.

**Pull request closed without merging**
